---
abstract: 'Calculate e-liquid recipes for DIY vaping'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-vaporcalc
requires:
  Defaults::Modern: 0.007
  Exporter::Tiny: 0
  JSON::MaybeXS: 0
  Term::ANSIColor: 4
  Term::ReadLine: 0
  Term::UI: 0
  Throwable: 0.2
resources:
  repository: git://github.com/avenj/app-vaporcalc.git
version: 0.001002
