---
abstract: 'Calculate e-liquid recipes for DIY vaping'
author:
  - 'Jon Portnoy <avenj@cobaltirc.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  List::Util: 0
  Scalar::Util: 0
  Test::Modern: 0.002
  Test::More: 0
  version: 0.77
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-vaporcalc
requires:
  Defaults::Modern: 0.007
  Exporter::Tiny: 0
  JSON::MaybeXS: 1.001
  Term::ANSIColor: 4
  Term::ReadLine: 0
  Term::UI: 0
  Text::ParseWords: 0
  Throwable: 0.2
resources:
  repository: git://github.com/avenj/app-vaporcalc.git
version: 0.003002
